export interface IAddress {
  id: number,
  user_id: number,
  address_line_1: string,
  address_line_2: string,
  town_city: string,
  county: string,
  postcode: string,
  country: string,
  is_default: boolean,
  is_billing_address: boolean,
  delivery_instr: string,
  full_name: string,
  phone: string,
}